### ISSUE TITLE
Blender 2.80

### ISSUE THREAD

**Issue by OscarOG** [konstvest/ei_figer#1]
Hi!

Any plans to make it **2.80** compatible?

**Comment by konstvest** [comment]
Hi!

Сompatibility with version 2.80 will be implemented a little later. Thank you for your comment.

**Comment by konstvest** [comment]
Add compatibility with Blender v2.80. You can find the addon panel in 3D view: press N, the menu is located on the right side under the tools tab. Please check it.

**Comment by OscarOG** [comment]
Hi,
It´s not working for me:

![capture](https://user-images.githubusercontent.com/22715737/65253376-d3b45200-dafa-11e9-8efe-e5042e59f292.png)

**Comment by konstvest** [comment]
Hi,
I suppose you need to remove the old addon and then install the new version.

**Comment by OscarOG** [comment]
I did a clean install, no old installation actually.

**Comment by konstvest** [comment]
information about upgrade to version 2.8 is still written near the addon?

**Comment by konstvest** [comment]
Please make sure that the downloaded file contains Blender version 2.80 (you can open it with text editors, line 20: 'blender': (2, 80, 0)). The version from the release section is for Blender v2.79. The new version is the source code, download ei_figer.py.

**Comment by OscarOG** [comment]
Sorry, downloaded the wrong version. It seems to work correctly.

Thank you!
